version: '3'

services:
  nginx:
    image: nginx:1.19.6-alpine
    ports: 
      - ${WEB_PORT:-80}:80
      - ${WEB_SSL_PORT:-443}:443
    volumes: 
      - ./nginx/:/etc/nginx/conf.d/
  php56:
    build: ./php56
    volumes:
      - ${WORK_SPACE}:/var/www/html
  php74:
    build: ./php74
    volumes:
      - ${WORK_SPACE}:/var/www/html
  mysql:
    image: mysql:5.7
    ports: 
      - ${MYSQL_PORT:-3306}:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASS:-password}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASS:-password}
      - TZ=Asia/Tokyo
  pgsql:
    image: postgres:13.1-alpine
    ports: 
      - ${PGSQL_PORT:-5432}:5432
    volumes:
      - ./pgsql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PGSQL_USER:-user}
      - POSTGRES_PASSWORD=${PGSQL_PASS:-password}
      - PGTZ=Asia/Tokyo
  mailhog:
    image: mailhog/mailhog
    ports:
      - ${MAIL_SMTP:-1025}:1025
      - ${MAIL_UI:-8025}:8025